name = "directlink"
main = "src/index.js"
compatibility_date = "2024-01-29"
workers_dev = false

[[kv_namespaces]]
binding = "KV"
id = "c97f11ca5cf8401e9caf2a0f52012b7f"

[vars]
PATH_PREFIX = ""
_123 = ""
_189 = ""
